apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: go-remoteaddr
  name: go-remoteaddr-service
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: go-remoteaddr
  type: LoadBalancer
status:
  loadBalancer: {}