apiVersion: v1
kind: Pod
metadata:
  name: go-remoteaddr
spec:
  containers:
  - name: go-remoteaddr
    image: gcr.io/makz-support-eap/go-remoteaddr
    ports:
    - containerPort: 8080
      name: porto
    readinessProbe:
      httpGet:
        path: /
        port: porto
      initialDelaySeconds: 5
      periodSeconds: 10
    livenessProbe:
      httpGet:
        path: /healthz
        port: porto
      initialDelaySeconds: 15
      periodSeconds: 20